In [2]:
import tensorflow as tf

In [6]:
print(tf.add(1,2))
print(tf.add([1, 2], [3, 4]))
print(tf.square(5))
print(tf.reduce_sum([1, 2]))
print(tf.square(5)+tf.square(2))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(29, shape=(), dtype=int32)


In [24]:
x = tf.constant([3, 4], shape=[1, 2])
y = tf.constant([5, 6], shape=[2, 1])
c = tf.matmul(x, y)
print(c)

tf.Tensor([[39]], shape=(1, 1), dtype=int32)


In [29]:
import numpy as np
ndarray=np.ones([3, 3])
print("Tensorflow operations convert numpy arrays to Tensors automatically")
tensor=tf.multiply(ndarray, 42)
print(tensor)
print("And Numpy operations convert numpy arrays to tensors automatically")
print(np.add(tensor, 1))
print(tensor.numpy())

Tensorflow operations convert numpy arrays to Tensors automatically
tf.Tensor(
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]], shape=(3, 3), dtype=float64)
And Numpy operations convert numpy arrays to tensors automatically
[[43. 43. 43.]
 [43. 43. 43.]
 [43. 43. 43.]]
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]
