In [8]:
from __future__ import absolute_import, division, print_function, unicode_literals
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import feature_column
from tensorflow.keras import layers

In [2]:
data = {'marks': [55,21,63,88,74,54,95,41,84,52],
        'grade': ['average','poor','average','good','good','average','good','average','good','average'],
        'point': ['c','f','c+','b+','b','c','a','d+','b+','c']}

In [3]:
df=pd.DataFrame(data)
df

marks    grade point
0     55  average     c
1     21     poor     f
2     63  average    c+
3     88     good    b+
4     74     good     b
5     54  average     c
6     95     good     a
7     41  average    d+
8     84     good    b+
9     52  average     c

In [4]:
# A utility method to show transromation from feature column
def demo(feature_column):
    feature_layer = layers.DenseFeatures(feature_column)
    print(feature_layer(data).numpy())

In [5]:
marks=feature_column.numeric_column("marks")
demo(marks)

Instructions for updating:
Use `tf.cast` instead.
[[55.]
 [21.]
 [63.]
 [88.]
 [74.]
 [54.]
 [95.]
 [41.]
 [84.]
 [52.]]


In [6]:
marks_bucket=feature_column.bucketized_column(marks, boundaries=[30, 40, 50 , 60, 70, 80, 90])
demo(marks_bucket)

Instructions for updating:
Use `tf.cast` instead.
[[0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]


In [7]:
grade=feature_column.categorical_column_with_vocabulary_list('grade', ['poor', 'average', 'good'])
grade_one_hot=feature_column.indicator_column(grade)
demo(grade_one_hot)

Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [9]:
point=feature_column.categorical_column_with_vocabulary_list('point', df['point'].unique())
point_one_hot=feature_column.indicator_column(point)
demo(point_one_hot)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]


In [10]:
point_embedding=feature_column.embedding_column(point, dimension=4)
demo(point_embedding)

[[-0.11970721  0.497541   -0.18733512  0.22350213]
 [ 0.08894373 -0.06903178 -0.558382   -0.1410427 ]
 [ 0.1835558   0.12181852  0.09177262 -0.5144051 ]
 [-0.21009284 -0.59196156  0.18121146 -0.9538177 ]
 [-0.7120029   0.00660467  0.2339806   0.22724395]
 [-0.11970721  0.497541   -0.18733512  0.22350213]
 [-0.18388176 -0.7233389  -0.07954244  0.5037864 ]
 [-0.08706743  0.15991832 -0.4232872   0.7122926 ]
 [-0.21009284 -0.59196156  0.18121146 -0.9538177 ]
 [-0.11970721  0.497541   -0.18733512  0.22350213]]


In [14]:
points_hashed=feature_column.categorical_column_with_hash_bucket('point', hash_bucket_size=4)
demo(feature_column.indicator_column(points_hashed))

Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


In [18]:
crossed_feature = feature_column.crossed_column([marks_bucket, grade], hash_bucket_size=10)
demo(feature_column.indicator_column(crossed_feature))

Instructions for updating:
The old _FeatureColumn APIs are being deprecated. Please use the new FeatureColumn APIs instead.
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
